const data = {
  products: [
    {
      name: 'Dog Slim Shirt',
      slug: 'dog-slim-shirt',
      category: 'Shirts',
      image: '/images/1dogcloth.jpg',
      price: '200',
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality shirts for dogs',
    },
    {
      name: 'Tactical Dog Collar ',
      slug: 'tactical-dog-collar',
      category: 'Collar',
      image: '/images/1dogcollars.jpg',
      price: '300',
      countInStock: 10,
      brand: 'adidas',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality collars for dogs',
    },
    {
      name: 'Automatic Pet Food Feeder',
      slug: 'automatic-pet-food-feeder',
      category: 'Feeder',
      image: '/images/1feeders.jpg',
      price: '2500',
      countInStock: 12,
      brand: 'Redmi',
      rating: 4.0,
      numReviews: 12,
      description: 'high quality Automatic Pet Food Feeder',
    },
    {
      name: ' Small Animal Sleep Cushion',
      slug: ' small animal sleep cushion',
      category: 'Cushion',
      image: '/images/1cousion.jpg',
      price: '100',
      countInStock: 5,
      brand: 'Vimal',
      rating: 4.1,
      numReviews: 5,
      description: 'high quality small animal sleep cushion',
    },
  ],
};

export default data;
